import {
  Product,
  Warehouse,
  WarehouseLocation,
  Receipt,
  Delivery,
  Transfer,
  Adjustment,
  StockMovement,
  User,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-001',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@stocksense.io',
    role: 'INVENTORY_MANAGER',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    warehouseName: 'Main Warehouse',
    createdAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'USR-002',
    name: 'Marcus Vance',
    email: 'marcus.vance@stocksense.io',
    role: 'WAREHOUSE_STAFF',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    warehouseName: 'Main Warehouse',
    createdAt: '2025-02-01T09:30:00Z',
  },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'WH-01',
    name: 'Main Warehouse',
    code: 'WH-MAIN',
    address: '104 Logistics Parkway, Industrial Zone, TX 75001',
    status: 'Active',
    manager: 'Sarah Jenkins',
    locationsCount: 6,
    productCount: 8,
    totalUnits: 4320,
  },
  {
    id: 'WH-02',
    name: 'Production Warehouse',
    code: 'WH-PROD',
    address: '42 Assembly Boulevard, North Plant, TX 75006',
    status: 'Active',
    manager: 'Carlos Mendez',
    locationsCount: 4,
    productCount: 5,
    totalUnits: 1850,
  },
  {
    id: 'WH-03',
    name: 'Warehouse 2 (East Facility)',
    code: 'WH-EAST',
    address: '880 Harbor Ring Road, Bayport, TX 77507',
    status: 'Active',
    manager: 'David Zhao',
    locationsCount: 3,
    productCount: 4,
    totalUnits: 980,
  },
];

export const INITIAL_LOCATIONS: WarehouseLocation[] = [
  {
    id: 'LOC-01',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    name: 'Rack A - Pallet High',
    code: 'RACK-A',
    zone: 'Zone 1 - Raw Materials',
    capacity: 2000,
    productCount: 3,
    currentQuantity: 1250,
  },
  {
    id: 'LOC-02',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    name: 'Rack B - Heavy Shelving',
    code: 'RACK-B',
    zone: 'Zone 1 - Raw Materials',
    capacity: 2500,
    productCount: 4,
    currentQuantity: 1820,
  },
  {
    id: 'LOC-03',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    name: 'Receiving Dock & Staging',
    code: 'REC-01',
    zone: 'Inbound Staging',
    capacity: 800,
    productCount: 2,
    currentQuantity: 350,
  },
  {
    id: 'LOC-04',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    name: 'Bulk Goods Yard',
    code: 'BULK-A',
    zone: 'Exterior Depot',
    capacity: 5000,
    productCount: 2,
    currentQuantity: 900,
  },
  {
    id: 'LOC-05',
    warehouseId: 'WH-02',
    warehouseName: 'Production Warehouse',
    name: 'Production Floor Staging',
    code: 'PROD-01',
    zone: 'Line Feeding',
    capacity: 1500,
    productCount: 3,
    currentQuantity: 920,
  },
  {
    id: 'LOC-06',
    warehouseId: 'WH-02',
    warehouseName: 'Production Warehouse',
    name: 'Assembly Buffer Rack',
    code: 'BUFF-01',
    zone: 'Sub-assembly',
    capacity: 1200,
    productCount: 2,
    currentQuantity: 930,
  },
  {
    id: 'LOC-07',
    warehouseId: 'WH-03',
    warehouseName: 'Warehouse 2 (East Facility)',
    name: 'Finished Goods Bay 1',
    code: 'FG-01',
    zone: 'Outbound Logistics',
    capacity: 2000,
    productCount: 2,
    currentQuantity: 580,
  },
  {
    id: 'LOC-08',
    warehouseId: 'WH-03',
    warehouseName: 'Warehouse 2 (East Facility)',
    name: 'Overflow Bin C',
    code: 'OVF-C',
    zone: 'Reserve Storage',
    capacity: 1500,
    productCount: 2,
    currentQuantity: 400,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'PRD-001',
    name: 'Steel Rod (12mm x 6m)',
    sku: 'STL-ROD-012',
    category: 'Raw Materials',
    unit: 'PCS',
    reorderLevel: 200,
    description: 'Structural grade carbon steel rebar for construction framing and reinforcement.',
    totalStock: 540,
    availableStock: 480,
    reservedStock: 60,
    status: 'In Stock',
    unitCost: 18.5,
    locations: [
      {
        warehouseId: 'WH-01',
        warehouseName: 'Main Warehouse',
        locationId: 'LOC-01',
        locationCode: 'RACK-A',
        quantity: 340,
      },
      {
        warehouseId: 'WH-02',
        warehouseName: 'Production Warehouse',
        locationId: 'LOC-05',
        locationCode: 'PROD-01',
        quantity: 200,
      },
    ],
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-09-20T14:30:00Z',
  },
  {
    id: 'PRD-002',
    name: 'Cement Bag (50kg Portland)',
    sku: 'CEM-BAG-050',
    category: 'Building Supplies',
    unit: 'BOX',
    reorderLevel: 150,
    description: 'High early strength Type I/II Portland hydraulic cement in moisture-proof sacks.',
    totalStock: 95,
    availableStock: 75,
    reservedStock: 20,
    status: 'Low Stock',
    unitCost: 12.0,
    locations: [
      {
        warehouseId: 'WH-01',
        warehouseName: 'Main Warehouse',
        locationId: 'LOC-04',
        locationCode: 'BULK-A',
        quantity: 95,
      },
    ],
    createdAt: '2025-01-12T11:15:00Z',
    updatedAt: '2026-09-24T09:00:00Z',
  },
  {
    id: 'PRD-003',
    name: 'Ergonomic Office Chair',
    sku: 'FUR-CHR-109',
    category: 'Finished Goods',
    unit: 'SET',
    reorderLevel: 30,
    description: 'High-back mesh ergonomic task chair with adjustable lumbar support and 3D armrests.',
    totalStock: 12,
    availableStock: 2,
    reservedStock: 10,
    status: 'Low Stock',
    unitCost: 185.0,
    locations: [
      {
        warehouseId: 'WH-03',
        warehouseName: 'Warehouse 2 (East Facility)',
        locationId: 'LOC-07',
        locationCode: 'FG-01',
        quantity: 12,
      },
    ],
    createdAt: '2025-01-18T16:20:00Z',
    updatedAt: '2026-09-22T11:10:00Z',
  },
  {
    id: 'PRD-004',
    name: 'Industrial Bolt M16 Grade 8.8',
    sku: 'BLT-M16-088',
    category: 'Fasteners',
    unit: 'PCS',
    reorderLevel: 800,
    description: 'High tensile zinc-plated hex head bolt with matching washer and locknut.',
    totalStock: 2450,
    availableStock: 2300,
    reservedStock: 150,
    status: 'In Stock',
    unitCost: 1.45,
    locations: [
      {
        warehouseId: 'WH-01',
        warehouseName: 'Main Warehouse',
        locationId: 'LOC-02',
        locationCode: 'RACK-B',
        quantity: 1650,
      },
      {
        warehouseId: 'WH-02',
        warehouseName: 'Production Warehouse',
        locationId: 'LOC-06',
        locationCode: 'BUFF-01',
        quantity: 800,
      },
    ],
    createdAt: '2025-01-20T08:45:00Z',
    updatedAt: '2026-09-24T16:20:00Z',
  },
  {
    id: 'PRD-005',
    name: 'Copper Wire Spool (2.5mm² 100m)',
    sku: 'WIR-CPR-250',
    category: 'Electrical',
    unit: 'PCS',
    reorderLevel: 50,
    description: 'Electrolytic copper stranded conductor with fire-retardant PVC insulation.',
    totalStock: 0,
    availableStock: 0,
    reservedStock: 0,
    status: 'Out of Stock',
    unitCost: 48.0,
    locations: [],
    createdAt: '2025-02-01T14:10:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'PRD-006',
    name: 'Safety Helmet - High Vis Yellow',
    sku: 'PPE-HLM-YEL',
    category: 'Safety & PPE',
    unit: 'PCS',
    reorderLevel: 40,
    description: 'ANSI Z89.1 Type 1 Class E industrial hard hat with 4-point ratcheting suspension.',
    totalStock: 180,
    availableStock: 160,
    reservedStock: 20,
    status: 'In Stock',
    unitCost: 16.5,
    locations: [
      {
        warehouseId: 'WH-01',
        warehouseName: 'Main Warehouse',
        locationId: 'LOC-03',
        locationCode: 'REC-01',
        quantity: 180,
      },
    ],
    createdAt: '2025-02-05T09:00:00Z',
    updatedAt: '2026-09-18T10:15:00Z',
  },
  {
    id: 'PRD-007',
    name: 'Wooden Panel Marine Plywood (18mm)',
    sku: 'PLY-MAR-018',
    category: 'Building Supplies',
    unit: 'PCS',
    reorderLevel: 100,
    description: 'BWP grade marine hardwood plywood sheet for structural moisture resistance.',
    totalStock: 320,
    availableStock: 300,
    reservedStock: 20,
    status: 'In Stock',
    unitCost: 42.0,
    locations: [
      {
        warehouseId: 'WH-01',
        warehouseName: 'Main Warehouse',
        locationId: 'LOC-01',
        locationCode: 'RACK-A',
        quantity: 220,
      },
      {
        warehouseId: 'WH-03',
        warehouseName: 'Warehouse 2 (East Facility)',
        locationId: 'LOC-08',
        locationCode: 'OVF-C',
        quantity: 100,
      },
    ],
    createdAt: '2025-02-10T13:40:00Z',
    updatedAt: '2026-09-21T15:00:00Z',
  },
  {
    id: 'PRD-008',
    name: 'Hydraulic Fluid ISO VG 46 (20L)',
    sku: 'LUB-HYD-046',
    category: 'Chemicals & Lubricants',
    unit: 'L',
    reorderLevel: 60,
    description: 'Anti-wear hydraulic oil for high-pressure industrial presses and mobile gear.',
    totalStock: 38,
    availableStock: 38,
    reservedStock: 0,
    status: 'Low Stock',
    unitCost: 65.0,
    locations: [
      {
        warehouseId: 'WH-02',
        warehouseName: 'Production Warehouse',
        locationId: 'LOC-05',
        locationCode: 'PROD-01',
        quantity: 38,
      },
    ],
    createdAt: '2025-02-15T15:20:00Z',
    updatedAt: '2026-09-23T11:45:00Z',
  },
];

export const INITIAL_RECEIPTS: Receipt[] = [
  {
    id: 'REC-1001',
    receiptNumber: 'REC-2026-089',
    supplier: 'ABC Steel Ltd',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    destinationLocationId: 'LOC-01',
    destinationLocationCode: 'RACK-A',
    expectedDate: '2026-09-28',
    createdBy: 'Sarah Jenkins',
    createdAt: '2026-09-24T09:15:00Z',
    status: 'Ready',
    notes: 'PO-8821: Standard delivery via flatbed truck. Forklift required for unloading.',
    items: [
      {
        productId: 'PRD-001',
        productName: 'Steel Rod (12mm x 6m)',
        sku: 'STL-ROD-012',
        unit: 'PCS',
        expectedQuantity: 200,
        receivedQuantity: 0,
      },
    ],
  },
  {
    id: 'REC-1002',
    receiptNumber: 'REC-2026-090',
    supplier: 'Global Components',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    destinationLocationId: 'LOC-03',
    destinationLocationCode: 'REC-01',
    expectedDate: '2026-09-29',
    createdBy: 'Sarah Jenkins',
    createdAt: '2026-09-24T14:30:00Z',
    status: 'Waiting',
    notes: 'Urgent restocking for Copper Wire spools and Safety Helmets.',
    items: [
      {
        productId: 'PRD-005',
        productName: 'Copper Wire Spool (2.5mm² 100m)',
        sku: 'WIR-CPR-250',
        unit: 'PCS',
        expectedQuantity: 80,
        receivedQuantity: 0,
      },
      {
        productId: 'PRD-006',
        productName: 'Safety Helmet - High Vis Yellow',
        sku: 'PPE-HLM-YEL',
        unit: 'PCS',
        expectedQuantity: 100,
        receivedQuantity: 0,
      },
    ],
  },
  {
    id: 'REC-1003',
    receiptNumber: 'REC-2026-088',
    supplier: 'Titan Fasteners Inc.',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    destinationLocationId: 'LOC-02',
    destinationLocationCode: 'RACK-B',
    expectedDate: '2026-09-23',
    createdBy: 'Sarah Jenkins',
    createdAt: '2026-09-22T08:00:00Z',
    status: 'Done',
    notes: 'Delivered in full. Quality inspection cleared by M. Vance.',
    items: [
      {
        productId: 'PRD-004',
        productName: 'Industrial Bolt M16 Grade 8.8',
        sku: 'BLT-M16-088',
        unit: 'PCS',
        expectedQuantity: 1000,
        receivedQuantity: 1000,
      },
    ],
  },
  {
    id: 'REC-1004',
    receiptNumber: 'REC-2026-091',
    supplier: 'Metro Industrial Supplies',
    warehouseId: 'WH-02',
    warehouseName: 'Production Warehouse',
    destinationLocationId: 'LOC-05',
    destinationLocationCode: 'PROD-01',
    expectedDate: '2026-10-02',
    createdBy: 'Sarah Jenkins',
    createdAt: '2026-09-25T11:00:00Z',
    status: 'Draft',
    notes: 'Draft requisition awaiting freight quote confirmation.',
    items: [
      {
        productId: 'PRD-008',
        productName: 'Hydraulic Fluid ISO VG 46 (20L)',
        sku: 'LUB-HYD-046',
        unit: 'L',
        expectedQuantity: 120,
        receivedQuantity: 0,
      },
    ],
  },
];

export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: 'DEL-2001',
    deliveryNumber: 'DO-2026-054',
    customer: 'XYZ Manufacturing',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    sourceLocationId: 'LOC-01',
    sourceLocationCode: 'RACK-A',
    deliveryDate: '2026-09-27',
    createdBy: 'Sarah Jenkins',
    createdAt: '2026-09-23T10:00:00Z',
    status: 'Ready',
    stage: 'packing',
    notes: 'Order SO-4421. Customer courier pickup at Dock 4.',
    items: [
      {
        productId: 'PRD-001',
        productName: 'Steel Rod (12mm x 6m)',
        sku: 'STL-ROD-012',
        unit: 'PCS',
        requestedQuantity: 60,
        pickedQuantity: 60,
        packedQuantity: 60,
        availableStock: 480,
      },
    ],
  },
  {
    id: 'DEL-2002',
    deliveryNumber: 'DO-2026-055',
    customer: 'BuildPro Industries',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    sourceLocationId: 'LOC-02',
    sourceLocationCode: 'RACK-B',
    deliveryDate: '2026-09-28',
    createdBy: 'Sarah Jenkins',
    createdAt: '2026-09-24T13:10:00Z',
    status: 'Waiting',
    stage: 'draft',
    notes: 'Staged for morning dispatch.',
    items: [
      {
        productId: 'PRD-004',
        productName: 'Industrial Bolt M16 Grade 8.8',
        sku: 'BLT-M16-088',
        unit: 'PCS',
        requestedQuantity: 150,
        pickedQuantity: 0,
        packedQuantity: 0,
        availableStock: 2300,
      },
    ],
  },
  {
    id: 'DEL-2003',
    deliveryNumber: 'DO-2026-053',
    customer: 'Alpha Constructions',
    warehouseId: 'WH-03',
    warehouseName: 'Warehouse 2 (East Facility)',
    sourceLocationId: 'LOC-07',
    sourceLocationCode: 'FG-01',
    deliveryDate: '2026-09-21',
    createdBy: 'Sarah Jenkins',
    createdAt: '2026-09-20T08:30:00Z',
    status: 'Done',
    stage: 'validated',
    notes: 'Delivered and signed by site manager.',
    items: [
      {
        productId: 'PRD-003',
        productName: 'Ergonomic Office Chair',
        sku: 'FUR-CHR-109',
        unit: 'SET',
        requestedQuantity: 10,
        pickedQuantity: 10,
        packedQuantity: 10,
        availableStock: 2,
      },
    ],
  },
];

export const INITIAL_TRANSFERS: Transfer[] = [
  {
    id: 'TRF-3001',
    transferNumber: 'TRF-2026-018',
    sourceWarehouseId: 'WH-01',
    sourceWarehouseName: 'Main Warehouse',
    sourceLocationId: 'LOC-01',
    sourceLocationCode: 'RACK-A',
    destWarehouseId: 'WH-02',
    destWarehouseName: 'Production Warehouse',
    destLocationId: 'LOC-05',
    destLocationCode: 'PROD-01',
    status: 'Waiting',
    createdBy: 'Sarah Jenkins',
    createdAt: '2026-09-25T08:15:00Z',
    notes: 'Replenishing production line buffer for morning assembly batch.',
    items: [
      {
        productId: 'PRD-001',
        productName: 'Steel Rod (12mm x 6m)',
        sku: 'STL-ROD-012',
        unit: 'PCS',
        availableQuantity: 340,
        transferQuantity: 50,
      },
    ],
  },
  {
    id: 'TRF-3002',
    transferNumber: 'TRF-2026-017',
    sourceWarehouseId: 'WH-01',
    sourceWarehouseName: 'Main Warehouse',
    sourceLocationId: 'LOC-02',
    sourceLocationCode: 'RACK-B',
    destWarehouseId: 'WH-02',
    destWarehouseName: 'Production Warehouse',
    destLocationId: 'LOC-06',
    destLocationCode: 'BUFF-01',
    status: 'Done',
    createdBy: 'Marcus Vance',
    createdAt: '2026-09-23T14:00:00Z',
    notes: 'Transferred via internal shuttle truck #2.',
    items: [
      {
        productId: 'PRD-004',
        productName: 'Industrial Bolt M16 Grade 8.8',
        sku: 'BLT-M16-088',
        unit: 'PCS',
        availableQuantity: 1650,
        transferQuantity: 200,
      },
    ],
  },
];

export const INITIAL_ADJUSTMENTS: Adjustment[] = [
  {
    id: 'ADJ-4001',
    adjustmentNumber: 'ADJ-2026-012',
    warehouseId: 'WH-01',
    warehouseName: 'Main Warehouse',
    locationId: 'LOC-04',
    locationCode: 'BULK-A',
    productId: 'PRD-002',
    productName: 'Cement Bag (50kg Portland)',
    sku: 'CEM-BAG-050',
    unit: 'BOX',
    systemQuantity: 98,
    physicalCount: 95,
    difference: -3,
    reason: 'Damaged',
    notes: '3 bags suffered puncture during pallet restack. Deemed unsellable.',
    status: 'Applied',
    createdBy: 'Marcus Vance',
    createdAt: '2026-09-24T09:00:00Z',
  },
  {
    id: 'ADJ-4002',
    adjustmentNumber: 'ADJ-2026-013',
    warehouseId: 'WH-02',
    warehouseName: 'Production Warehouse',
    locationId: 'LOC-05',
    locationCode: 'PROD-01',
    productId: 'PRD-008',
    productName: 'Hydraulic Fluid ISO VG 46 (20L)',
    sku: 'LUB-HYD-046',
    unit: 'L',
    systemQuantity: 40,
    physicalCount: 38,
    difference: -2,
    reason: 'Counting Error',
    notes: 'Cycle count discrepancy verified on shelf 2B.',
    status: 'Applied',
    createdBy: 'Marcus Vance',
    createdAt: '2026-09-23T11:45:00Z',
  },
];

export const INITIAL_MOVEMENTS: StockMovement[] = [
  {
    id: 'MOV-5001',
    timestamp: '2026-09-24T09:00:00Z',
    reference: 'ADJ-2026-012',
    referenceType: 'Adjustment',
    productId: 'PRD-002',
    productName: 'Cement Bag (50kg Portland)',
    sku: 'CEM-BAG-050',
    unit: 'BOX',
    fromWarehouse: 'Main Warehouse',
    fromLocation: 'BULK-A',
    quantity: -3,
    beforeQuantity: 98,
    afterQuantity: 95,
    reason: 'Damaged (Puncture during restack)',
    user: 'Marcus Vance',
  },
  {
    id: 'MOV-5002',
    timestamp: '2026-09-23T14:00:00Z',
    reference: 'TRF-2026-017',
    referenceType: 'Transfer Out',
    productId: 'PRD-004',
    productName: 'Industrial Bolt M16 Grade 8.8',
    sku: 'BLT-M16-088',
    unit: 'PCS',
    fromWarehouse: 'Main Warehouse',
    fromLocation: 'RACK-B',
    toWarehouse: 'Production Warehouse',
    toLocation: 'BUFF-01',
    quantity: -200,
    beforeQuantity: 1850,
    afterQuantity: 1650,
    reason: 'Internal Transfer replenishment',
    user: 'Marcus Vance',
  },
  {
    id: 'MOV-5003',
    timestamp: '2026-09-23T14:00:00Z',
    reference: 'TRF-2026-017',
    referenceType: 'Transfer In',
    productId: 'PRD-004',
    productName: 'Industrial Bolt M16 Grade 8.8',
    sku: 'BLT-M16-088',
    unit: 'PCS',
    fromWarehouse: 'Main Warehouse',
    fromLocation: 'RACK-B',
    toWarehouse: 'Production Warehouse',
    toLocation: 'BUFF-01',
    quantity: 200,
    beforeQuantity: 600,
    afterQuantity: 800,
    reason: 'Internal Transfer received',
    user: 'Marcus Vance',
  },
  {
    id: 'MOV-5004',
    timestamp: '2026-09-22T08:00:00Z',
    reference: 'REC-2026-088',
    referenceType: 'Receipt',
    productId: 'PRD-004',
    productName: 'Industrial Bolt M16 Grade 8.8',
    sku: 'BLT-M16-088',
    unit: 'PCS',
    toWarehouse: 'Main Warehouse',
    toLocation: 'RACK-B',
    quantity: 1000,
    beforeQuantity: 850,
    afterQuantity: 1850,
    reason: 'Purchase Receipt PO-7718 from Titan Fasteners Inc.',
    user: 'Sarah Jenkins',
  },
  {
    id: 'MOV-5005',
    timestamp: '2026-09-20T08:30:00Z',
    reference: 'DO-2026-053',
    referenceType: 'Delivery',
    productId: 'PRD-003',
    productName: 'Ergonomic Office Chair',
    sku: 'FUR-CHR-109',
    unit: 'SET',
    fromWarehouse: 'Warehouse 2 (East Facility)',
    fromLocation: 'FG-01',
    quantity: -10,
    beforeQuantity: 22,
    afterQuantity: 12,
    reason: 'Sales order dispatch to Alpha Constructions',
    user: 'Sarah Jenkins',
  },
  {
    id: 'MOV-5006',
    timestamp: '2026-09-18T10:15:00Z',
    reference: 'INIT-2026-001',
    referenceType: 'Opening Balance',
    productId: 'PRD-006',
    productName: 'Safety Helmet - High Vis Yellow',
    sku: 'PPE-HLM-YEL',
    unit: 'PCS',
    toWarehouse: 'Main Warehouse',
    toLocation: 'REC-01',
    quantity: 180,
    beforeQuantity: 0,
    afterQuantity: 180,
    reason: 'Initial system stock audit opening balance',
    user: 'Sarah Jenkins',
  },
];
